# @name info
GET {{endpoint}}/v2/info

###
@authHost = {{info.response.body.authorization_endpoint}}

# @name login
POST {{authHost}}/oauth/token
Authorization: Basic Y2Y6
Content-Type: application/x-www-form-urlencoded

client_id=cf&username={{username}}&password={{password}}&grant_type=password

### 
@token = {{login.response.body.access_token}}


# @name organiations
GET {{endpoint}}/v3/organizations
Authorization: Bearer {{token}}

###
@organization = {{organiations.response.body.resources[0].guid}}

GET {{endpoint}}/v2/organizations/{{organization}}/users?results-per-page=1
Authorization: Bearer {{token}}